{% set name = "lscsoft-glue" %}
{% set version = "2.0.0" %}
{% set sha256 = "9bdfaebe4c921d83d1e3d1ca24379a644665e9d7530e7070665f387767c66923" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - libpython  # [win]
    - pip
    - python
    - setuptools
  run:
    - ligo-segments
    - numpy
    - pyopenssl
    - python
    - python-pegasus-wms
    - six

test:
  imports:
    - glue
    - glue.gpstime
    - glue.iterutils
    - glue.lal
    - glue.ligolw
    - glue.ligolw.ilwd
    - glue.ligolw.tokenizer
    - glue.pipeline
    - glue.text_progress_bar
    - glue.utils
    - glue.workflow
  commands:
    # check links
    - conda inspect linkages -p ${PREFIX} ${PKG_NAME}  # [not win]
    - conda inspect objects -p ${PREFIX} ${PKG_NAME}  # [osx]

about:
  home: https://git.ligo.org/lscsoft/{{ name }}
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine
  description: |
    Glue is a collection of utilities for running data analysis pipelines
    for online and offline analysis as well as accessing various grid
    utilities.  It also provides the infrastructure for the segment
    database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
