{% set name = "lscsoft-glue" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7250b695da1db6c6fc034598c2a0e46103273a279ea170d60c2472770edc8f5
  patches:
    # skip re-building git_version.py
    - 0001-setup.py-skip-git-version-info-generation.patch

build:
  number: 0
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    # extras for cross compilation
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - libpython  # [win]
    - pip
    - python
    - setuptools
  run:
    - ligo-segments
    - numpy
    - pyopenssl
    - python
    - pyrxp
    - six

test:
  requires:
    - matplotlib-base
    - pip
  source_files:
    - test/
  imports:
    - glue
    - glue.iterutils
    - glue.lal
    - glue.ldbd
    - glue.pidfile  # [not win]
    - glue.pipeline
    - glue.segmentdb
  commands:
    # check requirements
    - python -m pip check
    # run some tests
    - python test/iterutils_verify.py
    - python test/lal_verify.py
    - python test/test_ldbd.py  # [not win]
    - python test/test_pidfile.py  # [not win]
    - python test/test_pipeline.py

about:
  home: https://git.ligo.org/lscsoft/glue.git
  doc_url: https://lscsoft.docs.ligo.org/glue/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine
  description: |
    Glue is a collection of utilities for running data analysis pipelines
    for online and offline analysis as well as accessing various grid
    utilities.  It also provides the infrastructure for the segment
    database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - robertbruntz
    - rpfisher
