{% set name = "lscsoft-glue" %}
{% set version = "1.59.2" %}
{% set sha256 = "5fa519df5e7301268b505bb78cdc55e8624f02a1e56bace856eb68a5509c758e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pyopenssl
    - numpy

test:
  imports:
    - glue
    - glue.ligolw
    - glue.segments

about:
  home: https://git.ligo.org/lscsoft/{{ name }}
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
