{% set name = "lscsoft-glue" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a242f29537f18957dbb07e6d9d20d7ebddc86c8325d4fa9e192cfa61a7c6ffbd

build:
  number: 0
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    # extras for cross compilation
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - libpython  # [win]
    - pip
    - python
    - setuptools
  run:
    - ligo-segments
    - numpy
    - pyopenssl
    - python
    - python-pegasus-wms 4
    - six

test:
  requires:
    - pip
  imports:
    - glue
    - glue.gpstime
    - glue.iterutils
    - glue.lal
    - glue.ligolw
    - glue.ligolw.ilwd
    - glue.ligolw.tokenizer
    - glue.pipeline
    - glue.text_progress_bar
    - glue.utils
    - glue.workflow
  commands:
    # check requirements
    - python -m pip check

about:
  home: https://git.ligo.org/lscsoft/glue.git
  doc_url: https://lscsoft.docs.ligo.org/glue/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine
  description: |
    Glue is a collection of utilities for running data analysis pipelines
    for online and offline analysis as well as accessing various grid
    utilities.  It also provides the infrastructure for the segment
    database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - robertbruntz
    - rpfisher
