{% set name = "lscsoft-glue" %}
{% set version = "1.60.0" %}
{% set sha256 = "c51a5703e33c8ca244ab50723dd5bf3984c3c6383838e77e9dd451678024a2a6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pyopenssl
    - numpy
    - ligo-segments

test:
  imports:
    - glue
    - glue.iterutils
    - glue.lal
    - glue.ligolw
    - glue.pipeline
  commands:
    # check links
    - conda inspect linkages -p ${PREFIX} ${PKG_NAME}  # [not win]
    - conda inspect objects -p ${PREFIX} ${PKG_NAME}  # [osx]

about:
  home: https://git.ligo.org/lscsoft/{{ name }}
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
