{% set name = "lscsoft-glue" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 80884ec79eec098ba30c6d7dd413601d5df399f54b9affe034f3fc48a4f5de27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
  run:
    - igwn-segments
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
    - pytest
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show lscsoft-glue
    # run some tests
    - python -m pytest -ra -v --pyargs glue.tests

about:
  home: https://git.ligo.org/lscsoft/glue.git
  doc_url: https://lscsoft.docs.ligo.org/glue/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Grid LSC User Engine
  description: |
    Glue is a collection of utilities for running data analysis pipelines
    for online and offline analysis as well as accessing various grid
    utilities.  It also provides the infrastructure for the segment
    database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
    - robertbruntz
    - rpfisher
