appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YoPZ2CqQDLk0I2AfAUW58X/zfvMx0+QsmCe37FAaY77BbrtM1v3N7zKP5Y9dyQi46OhQrZNXJ2G9XNXDJgEDPS3yn+bFhwCwgA4YYkXKO+H9qeoiG5bN5P60lYOfeIsJW57E3UipsoKJwrHVPP7yakCOAcSR6eR+LsCwBrTpP7J5nT0H4bWidzp1gg8k1hSzV6lBwkptJpyx+iLTEw4AmA8yxF5ZvgZhXfgbuHalIEQtKeYpK0CNKIoJzjcVsAnswRv7ZS62CrvIcwkzi68tZqzojvCawch2mpNmuqnfIfa/xW287KA3EGIIQzQ2tUsWkLh2GX6B/rbMcdcp2JSRRhQ+UJ4xfC97WJyxojxSo18Wmp+tvixEWKR7AsEt8X+4OwQCJDLCC7bImoNQX4RojqpWM1IgGDFV3HExBwBjnxIEqnvpsO8GyjSjm7CtcTg40WQO8CQbf5QAyLkCYA3ODE9Eyac58X+yuVF07iEiVymddIJo63NZWw4X2O/q9K2V5sifTjDaw2ckGw8JfVbz9moXgSQd/a/4bKYFF1NsuPX/Nt23Hzl2+mwadHcTI/3MdLgXjRNWbKHjHsNjJvbhBaVIgIHi2ilrLd1YV5ptfHwi4qwE0kmrrDRVJG4fzBWmZ7hd73/3/on3d2ZyvmAKmhIzirQ1/RA/UGs4gBT8QTg=}
provider:
  linux: azure
  osx: azure
  win: azure
conda_forge_output_validation: true
