travis:
  secure:
    BINSTAR_TOKEN: WbQO+6YSsiwapGBxf/Ni0HZ18SvS86/cS5t399pK9aBxFjArjyc8wNI08/BfpCQm+EmQCA3S07pNMPM5K8RAcCeq1kHJ4V5si2chZBxfcx9PEWnGmoqQYYb3S/4IrZyS3MwChEbKWe7pYHMOMxlLdPLLkQ44fNMAWPOlKCiRxWbU1mQghUn/uFe9oZctbsMPSZKp2bAwapub/S0glMQwflSezr5L244BOZmicpS3qeI9SXj1SI+c6bQIH4rFEfMssB641E9ubJrAwU8m3ZXFWf+xCQsrQcJWopBmkKbr3YRNIXsTD/x8Lb+wXmiaaECLfpv7MiUTRUT215qNKO1Ny5hnSh/qL1MNqrK5bj871UOWsMrw1QWmjAizD9GsUyMWYO8ukpkfcvtJ5W8KnK0upb9KVhGC5OWwpzA/reKpocBOZNusdkNE7MoofFN/NpzZD+ZBxuYaHlnfkC0d8z6WeLbInDGN1ehvXAqKPmynAW7s3mRH6Z5Osbnt8qlAH64g02v3C4fyHoQLs8XD6dEcAsxPpjE8G0Xy5LiuT56AxUpfEqV6lUFodU4pRJm68BiwLIWZfXTv+jMGvVP1OZBG2EkTZ+Mbww/Gc+F/WtBtnaSZPS5uAe3zYixL9uSk0ze2VsPS6p1JotBzsd1ch7l1C/X4MGILYUxb3FMmuSN85Es=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
